KannadaWebApp/Controllers/LanguageController.cs
using KannadaWebApp.Models;
using KannadaWebApp.Models.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KannadaWebApp.Controllers
{
    public class LanguageController : Controller
    {
        IHindiKannadaADORepository ADORepo = new HindiKannadaADORepository();
        // GET: Language
        public ActionResult AddWords()
        {
            LanguageCardDTO languageCardDTO = new LanguageCardDTO();
            IEnumerable<string> categories = ADORepo.GetAllCategories();
            languageCardDTO.categoriesForDropdown = GetAllCategoriesSelectList(categories);
            return View(languageCardDTO);
        }

        public ActionResult SaveLanguagePair(LanguageCardDTO languageCardDTO)
        {
            int isInserted = ADORepo.SaveLanguagePair(languageCardDTO);
            return PartialView();
        }


        //public ActionResult someNotificationThingyToTellEntryAdded

        #region Private Methods
        private IEnumerable<SelectListItem> GetAllCategoriesSelectList(IEnumerable<string> categories)
        {
            var selectList = new List<SelectListItem>();

            foreach (var category in categories)
            {
                selectList.Add(new SelectListItem()
                {
                    Value = category,
                    Text = category
                });
            }
            return selectList;
        }
        #endregion
    }
}

KannadaWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-light navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add Words", "AddWords", "Language")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")﻿
    @RenderSection("scripts", required: false)
</body>
</html>